[package]
name = "HexCompare"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.12.1"
time = "0.3.41"
log = "0.4.27"
once_cell = "1.21.3"
biologischer-log = { git = "https://github.com/BioTomateDE/rust-biologischer-log.git" }
